apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: banking
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "password123"  # placeholder â€” replace with your real password
  DB_HOST: pg-bank-postgresql
  DB_PORT: "5432"
