apiVersion: v1
kind: Pod
metadata:
  name: psql-client
  namespace: banking
  labels:
    app: psql-client
spec:
  containers:
    - name: psql-client
      image: registry-1.docker.io/bitnami/postgresql:latest
      command: ["sleep", "infinity"]
